version: '3'
services:
  db:
    container_name: ultra-tech-test-cars-mysql
    image: mysql:5
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_TCP_PORT: 13306
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: ms
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: cars
    network_mode: host
  redis:
    container_name: ultra-tech-test-cars-redis
    build: ./docker/redis
    image: ultra-tech-test/cars-redis:latest
    network_mode: host
    environment:
      REDIS_MASTER_PORT_NUMBER: 16379
  ms:
    container_name: ultra-tech-test-cars-ms
    build:
      context: .
      dockerfile: ./docker/ms/Dockerfile
    image: ultra-tech-test/cars-ms:latest
    network_mode: host
    depends_on:
      - db
      - redis
