export const ApiDescription: string = '## Endpoints\n\
\n\
- The [Cars](#cars-endpoint) endpoint\n\
- The [Cars Manufacturer](#cars-manufacturer-endpoint) endpoint\n\
- The [Cars Owners](#cars-owners-endpoint) endpoint\n\
- The [Cars Jobs](#cars-jobs-endpoint) endpoint\n\
- The [Manufacturers](#manufacturers-endpoint) endpoint (not required but useful for tests)\n\
\n\
## Cars endpoint\n\
\n\
An endpoint to manage cars.\n\
\n\
### Create cars\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Create one with autogenerated id\n\
$ curl -X POST http://localhost:3000/cars  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"1","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":3000}\'\n\
$ curl -X POST http://localhost:3000/cars  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"2","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":4000}\'\n\
$ curl -X POST http://localhost:3000/cars  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"2","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":5000}\'\n\
\n\
# Create one with custom id\n\
$ curl -X PUT http://localhost:3000/cars/1  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"1","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":3000}\'\n\
$ curl -X PUT http://localhost:3000/cars/2  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"2","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":4000}\'\n\
$ curl -X PUT http://localhost:3000/cars/3  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"1","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":5000}\'\n\
\n\
# Create many\n\
$ curl -X POST http://localhost:3000/cars/bulk  -H \'Content-Type:application/json\' -d \'{"bulk":[{"manufacturerId":"1","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":3000},{"id":"4","manufacturerId":"1","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":4000},{"id":"5","manufacturerId":"2","firstRegistrationDate":"2018-07-26T08:17:30.635Z","price":5000}]}\'\n\
```\n\
\n\
### Update cars\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Update\n\
$ curl -X PATCH http://localhost:3000/cars/1  -H \'Content-Type:application/json\' -d \'{"firstRegistrationDate":"2017-07-30T08:17:30.635Z"}\'\n\
$ curl -X PATCH http://localhost:3000/cars/2  -H \'Content-Type:application/json\' -d \'{"price":2000}\'\n\
\n\
# Replace\n\
$ curl -X PUT http://localhost:3000/cars/3  -H \'Content-Type:application/json\' -d \'{"manufacturerId":"2","firstRegistrationDate":"2018-07-30T08:17:30.635Z","price":15000}\'\n\
```\n\
\n\
### Retrieve cars\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# All\n\
$ curl -X GET http://localhost:3000/cars\n\
\n\
# One\n\
$ curl -X GET http://localhost:3000/cars/1\n\
```\n\
\n\
## Cars Manufacturer endpoint\n\
\n\
An endpoint to retreive cars manufacturer.\n\
\n\
#### Using curl\n\
\n\
```sh\n\
$ curl -X GET http://localhost:3000/cars/1/manufacturer\n\
```\n\
\n\
## Cars Owners endpoint\n\
\n\
An endpoint to manage cars owners.\n\
\n\
### Create cars owners\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Create one with autogenerated id\n\
$ curl -X POST http://localhost:3000/cars/1/owners  -H \'Content-Type:application/json\' -d \'{"name":"Test1 Auto", "purchaseDate":"2019-01-22T08:17:30.635Z"}\'\n\
$ curl -X POST http://localhost:3000/cars/1/owners  -H \'Content-Type:application/json\' -d \'{"name":"Test2 Auto", "purchaseDate":"2019-01-22T08:17:30.635Z"}\'\n\
\n\
# Create one with custom id\n\
$ curl -X PUT http://localhost:3000/cars/1/owners/1  -H \'Content-Type:application/json\' -d \'{"name":"Test2", "purchaseDate":"2019-01-22T08:17:30.635Z"}\'\n\
$ curl -X PUT http://localhost:3000/cars/1/owners/2  -H \'Content-Type:application/json\' -d \'{"name":"Test3", "purchaseDate":"2019-01-22T08:17:30.635Z"}\'\n\
\n\
# Create many\n\
$ curl -X POST http://localhost:3000/cars/bulk  -H \'Content-Type:application/json\' -d \'{"bulk":[{"name":"Test3 Auto", "purchaseDate":"2019-01-22T08:17:30.635Z"}, {"id":"3","name":"Test3", "purchaseDate":"2019-01-22T08:17:30.635Z"}]}\'\n\
```\n\
\n\
### Update cars owners\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Update\n\
$ curl -X PATCH http://localhost:3000/cars/1  -H \'Content-Type:application/json\' -d \'{"purchaseDate":"2018-12-22T08:17:30.635Z"}\'\n\
$ curl -X PATCH http://localhost:3000/cars/2  -H \'Content-Type:application/json\' -d \'{"name":"Test2 Up"}\'\n\
\n\
# Replace\n\
$ curl -X PUT http://localhost:3000/cars/3  -H \'Content-Type:application/json\' -d \'{"name":"Test3 Up","purchaseDate":"2018-12-22T08:17:30.635Z"}\'\n\
```\n\
\n\
### Retrieve cars owners\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# All\n\
$ curl -X GET http://localhost:3000/cars/1/owners\n\
\n\
# One\n\
$ curl -X GET http://localhost:3000/cars/1/owners/1\n\
```\n\
\n\
## Cars Jobs endpoint\n\
\n\
An endpoint to trigger a process which will automatically remove the owners who bought their cars before the last\n\
18 months and apply a discount of 20% to all cars having a date of first registration between 12 and\n\
18 months.\n\
\n\
### Create cars jobs\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Create one\n\
$ curl -X POST http://localhost:3000/cars/jobs\n\
```\n\
\n\
### Retrieve cars jobs\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# All\n\
$ curl -X GET http://localhost:3000/cars/jobs\n\
\n\
# One\n\
$ curl -X GET http://localhost:3000/cars/jobs/1\n\
```\n\
\n\
## Manufacturers endpoint\n\
\n\
An endpoint to manage manufacturers.\n\
\n\
### Create manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Create one with autogenerated id\n\
$ curl -X POST http://localhost:3000/manufacturers -H \'Content-Type:application/json\'  -d \'{"name":"Test Auto 1"}\'\n\
$ curl -X POST http://localhost:3000/manufacturers  -H \'Content-Type:application/json\' -d \'{"name":"Test Auto 2","siret":20}\'\n\
$ curl -X POST http://localhost:3000/manufacturers  -H \'Content-Type:application/json\' -d \'{"name":"Test Auto 3"}\'\n\
\n\
# Create one with custom id\n\
$ curl -X PUT http://localhost:3000/manufacturers/1  -H \'Content-Type:application/json\' -d \'{"name":"Test 1"}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/2  -H \'Content-Type:application/json\' -d \'{"name":"Test 2","siret":21}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/3  -H \'Content-Type:application/json\' -d \'{"name":"Test 3"}\'\n\
\n\
# Create many\n\
$ curl -X POST http://localhost:3000/manufacturers/bulk  -H \'Content-Type:application/json\' -d \'{"bulk":[{"name":"Test Bulk 1"}, {"id":"4","name":"Test Bulk 2"}]}\'\n\
```\n\
\n\
### Update manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Update\n\
$ curl -X PATCH http://localhost:3000/manufacturers/1  -H \'Content-Type:application/json\' -d \'{"name":"Test 1 Up"}\'\n\
$ curl -X PATCH http://localhost:3000/manufacturers/2  -H \'Content-Type:application/json\' -d \'{"siret":2}\'\n\
$ curl -X PATCH http://localhost:3000/manufacturers/3  -H \'Content-Type:application/json\' -d \'{"name":"Test 3 Up","phone":"+33610203040"}\'\n\
\n\
# Replace\n\
$ curl -X PUT http://localhost:3000/manufacturers/1  -H \'Content-Type:application/json\' -d \'{"name":"Test 1 Replace"}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/3  -H \'Content-Type:application/json\' -d \'{"name":"Test 3 Replace","phone":"+33650607080"}\'\n\
```\n\
\n\
### Retrieve manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# All\n\
$ curl -X GET http://localhost:3000/manufacturers\n\
\n\
# One\n\
$ curl -X GET http://localhost:3000/manufacturers/1\n\
```';
