export const ApiDescription: string = '## Manfuacturers\n\
\n\
### Create manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Create with autogenerated id\n\
$ curl -X POST http://localhost:3000/manufacturers -d \'{"name":"Test Auto 1"}\'\n\
$ curl -X POST http://localhost:3000/manufacturers -d \'{"name":"Test Auto 2"}\'\n\
$ curl -X POST http://localhost:3000/manufacturers -d \'{"name":"Test Auto 3"}\'\n\
\n\
# Create with custom id\n\
$ curl -X PUT http://localhost:3000/manufacturers/1 -d \'{"name":"Test 1"}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/2 -d \'{"name":"Test 2"}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/3 -d \'{"name":"Test 3"}\'\n\
```\n\
\n\
### Update manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# Update\n\
$ curl -X PATCH http://localhost:3000/manufacturers/{id} -d \'{"name":"Test Auto 1 Up"}\'\n\
$ curl -X PATCH http://localhost:3000/manufacturers/{id} -d \'{"siret":2}\'\n\
$ curl -X PATCH http://localhost:3000/manufacturers/{id} -d \'{"name":"Test Auto 3 Up","phone":"+33610203040"}\'\n\
\n\
# Replace\n\
$ curl -X PUT http://localhost:3000/manufacturers/1 -d \'{"name":"Test 1 Up"}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/2 -d \'{"siret":12}\'\n\
$ curl -X PUT http://localhost:3000/manufacturers/3 -d \'{"name":"Test 3 Up","phone":"+33650607080"}\'\n\
```\n\
\n\
### Retrieve manufacturers\n\
\n\
#### Using curl\n\
\n\
```sh\n\
# All\n\
$ curl -X GET http://localhost:3000/manufacturers\n\
\n\
# One\n\
$ curl -X GET http://localhost:3000/manufacturers/1\n\
```';
